name: uji_keterampilan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: 5.7.0
  dio: 5.3.2
  google_fonts: 4.0.5
  cached_network_image: 3.2.3
  carousel_slider: 4.2.1
  lazy_load_indexed_stack: 0.1.4
  flutter_easyloading: 3.0.5
  loading_animation_widget: 1.2.0+4
  flutter_svg: 2.0.7
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.3
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/models/
  uses-material-design: true

